### ISSUE TITLE
Form filefield is a bit ugly

### ISSUE THREAD

**Issue by halfnibble** [sveetch/crispy-forms-foundation#22]
Using Foundation 5, the filefield layout generated is less than ideal. 

It would at least be nice to get a little space between the file name and the "clear" checkbox. 

![invoice-file-field-crispy](https://cloud.githubusercontent.com/assets/5139752/7991688/ea46fd18-0aae-11e5-9f81-30a892e36d73.png)

**Comment by sveetch** [comment]
Sorry but this is not really the point of crispy-forms-foundation or even django-crispy-forms, this is about styling so much more about Foundation or your own stylesheets.

Filefield are just <input type="file"> and actually not treated differently than a text input. And the clearing part comes from Django.

Maybe we could add a special layout element for this, but Foundation wont style it differently, we probably have to make it ourself. I'm not confident about adding too much styling addons in this App.

Maybe you could give us a pull request about this.

**Comment by PhilipGarnero** [comment]
@halfnibble I've made a [little widget](https://github.com/PhilipGarnero/django-foundation-filefield-widget) using foundation for filefields.
Check it out.

**Comment by sveetch** [comment]
Kept this issue open to watch for "File Upload Button" Foundation6 implementation, sadly this component only mask input but does not expose upload file location when a file has been selected.

So finally dropped the idea.
