### ISSUE TITLE
TemplateSyntaxError at /login/  crispy tag's template_pack argument should be in ('bootstrap', 'uni_form', 'bootstrap3')

### ISSUE THREAD

**Issue by compfaculty** [sveetch/crispy-forms-foundation#24]
All made by manual but I get this error.
settings.py
INSTALLED_APPS = [
    'flat',  # django-flat-theme must be BEFORE contrib.admin

    # Django apps
    'django.contrib.admin',
    'django.contrib.admindocs',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.sites',
    'django.contrib.messages',
    'django.contrib.humanize',
    'django.contrib.syndication',
    'django.contrib.staticfiles',

    # Third party apps
    'compressor',
    'crispy_forms',
    'crispy_forms_foundation',
    'django_extensions',
    # Local apps
    'base',
]

CRISPY_TEMPLATE_PACK = 'foundation-5'

**Comment by sveetch** [comment]
It's pretty strange since your settings.CRISPY_TEMPLATE_PACK is correct. What version of crispy_forms are you using ?

I didnt look at it, maybe the 1.5.x is adding some restrictions.

**Comment by sveetch** [comment]
And by the way, can you paste me your full exception in a pastebin or alike ?

**Comment by compfaculty** [comment]
TemplateSyntaxError at /login/

crispy tag's template_pack argument should be in ('bootstrap', 'uni_form', 'bootstrap3')

Request Method: 	GET
Request URL: 	http://localhost:8000/login/
Django Version: 	1.8.3
Exception Type: 	TemplateSyntaxError
Exception Value: 	

crispy tag's template_pack argument should be in ('bootstrap', 'uni_form', 'bootstrap3')

Exception Location: 	/home/alex/py3/lib/python3.4/site-packages/crispy_forms/templatetags/crispy_forms_tags.py in do_uni_form, line 285
Python Executable: 	/home/alex/py3/bin/python
Python Version: 	3.4.0
Python Path: 	

['/home/alex/PycharmProjects/JobTest',
 '/home/alex/py3/lib/python3.4',
 '/home/alex/py3/lib/python3.4/plat-x86_64-linux-gnu',
 '/home/alex/py3/lib/python3.4/lib-dynload',
 '/usr/lib/python3.4',
 '/usr/lib/python3.4/plat-x86_64-linux-gnu',
 '/home/alex/py3/lib/python3.4/site-packages',
 '/home/alex/PycharmProjects/JobTest/JobTest',
 '/home/alex/PycharmProjects/JobTest/apps',
 '/home/alex/PycharmProjects/JobTest/libs']

Server time: 	Sun, 23 Aug 2015 07:00:19 -0700
Error during template rendering

In template /home/alex/PycharmProjects/JobTest/apps/base/templates/base/login.html, error at line 8
crispy tag's template_pack argument should be in ('bootstrap', 'uni_form', 'bootstrap3')
1 	{% extends 'base.html' %}
2 	{% load crispy_forms_tags %}
3 	
4 	{% block main_content %}
5 	<div class="container">
6 	    <div class="row">
7 	        <div class="col-md-6 col-md-offset-3">
8 	                  
      {% crispy login_form %}      
9 	            {% if messages %}
10 	            <ul class="messages">
11 	                {% for message in messages %}
12 	                <li
13 	                {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
14 	                {% endfor %}
15 	            </ul>
16 	            {% endif %}
17 	        </div>
18 	    </div>

**Comment by compfaculty** [comment]
crispy-forms-foundation==0.5.2
django-crispy-forms==1.5.1

**Comment by sveetch** [comment]
Seems you are using the tag like this "{% crispy form 'bootstrap' %}" in your template with a form that does not set an helper, can you confirm ?

You should avoid this exception either adding an helper to your form or defining the setting `CRISPY_ALLOWED_TEMPLATE_PACKS` with something like this :
```
CRISPY_ALLOWED_TEMPLATE_PACKS = ('bootstrap', 'uni_form', 'bootstrap3', 'foundation-5')
```

I'm awaiting your confirm about crispy tag usage to update the documentation about this problem, thanks.

**Comment by compfaculty** [comment]
Looks like CRISPY_ALLOWED_TEMPLATE_PACKS = ('bootstrap', 'uni_form', 'bootstrap3', 'foundation-5') helps. After all, I made a hard mix with crispy-forms and your module, think it was a problem too. Tag itself is ok - 
My form
```python
class LoginForm(forms.Form):
    login = forms.CharField(label=_('Login'), widget=forms.TextInput(attrs={'required':''}), required=True, max_length=30)
    password = forms.CharField(label=_('Password'), widget=forms.TextInput(attrs={'required':''}), required=True, max_length=30)

    def __init__(self, *args, **kwargs):
        # Init layout form with crispy
        self.helper = FormHelper()
        self.helper.form_id = 'id-LoginForm'
        self.helper.form_method = 'post'
        self.helper.form_action = '.'
        self.helper.form_error_title = 'Oooops...'
        self.helper.form_show_labels = False
        # self.helper.attrs = {'data_abide': ''}
        self.helper.form_action = '.'
        self.helper.layout = Layout(
            Fieldset(
                _('Authentification'),
                'login',
                'password',
            ),
            ButtonHolder(

                Submit('submit', _('Send'),css_class='large-offset-6 margintop-10  button round'),
            ),
        )

        super(LoginForm, self).__init__(*args, **kwargs)
```
View
```python
def login_view(request):
    redirect_url = request.GET.get('next')
    if request.method == 'POST':
        login_form = LoginForm(request.POST)
        if login_form.is_valid():
            username = login_form.cleaned_data['login']
            password = login_form.cleaned_data['password']
            user = authenticate(username=username, password=password)

            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect(redirect_url or "base:home")
                else:
                    messages.error(request, "user is not active")
            else:
                messages.error(request, "ask your administrator to create account for you!")
        return render(request, "base/login.html", context={'login_form': login_form})
```
Template
```
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block main_content %}
<div class="container">
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            {% crispy login_form %}
            {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                <li
                {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
            {% endif %}
        </div>
    </div>
</div>
{% endblock main_content %}
```

**Comment by compfaculty** [comment]
Great support as for open source project, David ;-)  Thanks a lot!

**Comment by sveetch** [comment]
Reopening this until i update the doc about settings.CRISPY_ALLOWED_TEMPLATE_PACKS to set because it seems a requirement since crispy 1.5.x

**Comment by pauline-rugwevera** [comment]
Thank you so much. ran into similar problem, couldnt solve it for days. You saved me

**Comment by askarsaparov** [comment]
I had this error too
