### ISSUE TITLE
CSS classes bugs with crispy>=1.5.x

### ISSUE THREAD

**Issue by sveetch** [sveetch/crispy-forms-foundation#25]
Seems css classes are not correct with crispy 1.5.x, like Submit() that should be "submit button" but appears to be "btn btn-primary". 

Some layout element have internal switch to fallback on some default value depending on used template pack. 

Why did it work before and why it don't now ? Have to test on demo.

**Comment by sveetch** [comment]
Ok this is confirmed

**Comment by bionikspoon** [comment]
What's happening:
`crispy_forms_foundation` is setting the styles as class variables:

```python
class Button(crispy_forms_layout.Button):  # buttons.py 90
    input_type = 'button'
    field_classes = 'button'
```

then `crispy_forms` is saying thanks, but no thanks, with its hard-coded, un-subclassable `Button` class:

```python
class Button(BaseInput):  # crispy_forms/layout.py
    input_type = 'button'
    def __init__(self, *args, **kwargs):
        self.field_classes = 'button' if get_template_pack() == 'uni_form' else 'btn no-thank-you'
        super(Button, self).__init__(*args, **kwargs)
```

I think the solution is to subclass `crispy_forms_layout.BaseInput` directly insead of `crispy_forms_layout.Button`.

**Comment by sveetch** [comment]
Nice, it make sense, i have to see why i inherited from Button, maybe an old stupid choice.
