### ISSUE TITLE
Foundation 6 Support

### ISSUE THREAD

**Issue by getup8** [sveetch/crispy-forms-foundation#27]
Is Foundation 6 support being worked on?

**Comment by sveetch** [comment]
Working on ? No. But planned yes.

F6 is a little too fresh for now, i dont have any project using it yet.

By the way, from what i remember, F6 forms are not so different from F5, no ?

**Comment by odarbelaeze** [comment]
What you mean is that if the markup is the same, the template pack would work just fine?

**Comment by sveetch** [comment]
Yep, the python code and template pack are only about to build some markup, positionning some css classes and all, there is no such magic. If the markup is the same, it will work with F5 template pack.

**Comment by flesser** [comment]
One change made in Foundation 6 is that the `<fieldset>` element is no longer styled by itself. It now requires the `.fieldset` class to be styled ([see docs](http://foundation.zurb.com/sites/docs/forms.html#fieldset-styles)).

For my current project, I modified `fieldset.html` to always contain that class ([see diff](https://github.com/flesser/crispy-forms-foundation/commit/3c7ac3284c7b4fd4e45de81bfe117a476ca120f8)). It doesn't hurt in Foundation 5 and is required for Foundation 6.

**Comment by sveetch** [comment]
@flesser thanks for the brief

So finally, i have to open a new template pack for F6. Will see how to do this without to duplicate and maintain too much markup for both packs

**Comment by flesser** [comment]
I found some more things and started to collect them in #29

**Comment by ppo** [comment]
Hi, what's the status of F6? Thanks.

**Comment by sveetch** [comment]
It's on my todo list in the 'soon' section, before starting it (possibly starting from this PR) i wanted to add some unittests for sanity.

I can't give you a date, eventually in the way of february.

**Comment by sveetch** [comment]
It's ok, Foundation 6 support has been added with 0.6.0 (commit 45a6d64)

**Comment by ppo** [comment]
👍 Great, thanks :-)
