### ISSUE TITLE
Django 1.11 support?

### ISSUE THREAD

**Issue by m-sanders** [sveetch/crispy-forms-foundation#32]
Noticed that this does not support Django 1.11.

Update: I had issues getting the test suite to run locally. Happy to resolve this issue if you have any pointers?

**Comment by sveetch** [comment]
You're welcome.

I'm rewriting Makefile, docs and pytest config so there will be an explicit procedure to install and run tests. Expect it soon.

**Comment by sveetch** [comment]
I finished the rewriting and finally tested with Django 1.11 and validated its support.

You can find documentation about installing everything to run tests here: http://crispy-forms-foundation.readthedocs.io/en/latest/development.html#install-for-development

Open a new issue if you find a bug with Django 1.11

**Comment by m-sanders** [comment]
Amazing. Thank you.
